### ISSUE TITLE
Error ccurred on Mac 10.15.4

### ISSUE THREAD

**Issue by jackple** [izonder/anny#2]
`
  g++ -o /node_src/node-v12.16.3/out/Release/obj.target/v8_compiler/deps/v8/src/compiler/common-operator-reducer.o ../deps/v8/src/compiler/common-operator-reducer.cc '-DV8_GYP_BUILD' '-DV8_TYPED_ARRAY_MAX_SIZE_IN_HEAP=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DV8_TARGET_ARCH_X64' '-DV8_EMBEDDER_STRING="-node.35"' '-DENABLE_DISASSEMBLER' '-DV8_PROMISE_INTERNAL_FIELD_COUNT=1' '-DENABLE_MINOR_MC' '-DV8_INTL_SUPPORT' '-DV8_USE_SNAPSHOT' '-DV8_CONCURRENT_MARKING' '-DV8_ENABLE_LAZY_SOURCE_POSITIONS' '-DV8_EMBEDDED_BUILTINS' '-DV8_USE_SIPHASH' '-DDISABLE_UNTRUSTED_CODE_MITIGATIONS' '-DV8_WIN64_UNWINDING_INFO' '-DV8_ENABLE_REGEXP_INTERPRETER_THREADED_DISPATCH' '-DUCONFIG_NO_SERVICE=1' '-DU_ENABLE_DYLOAD=0' '-DU_STATIC_IMPLEMENTATION=1' '-DU_HAVE_STD_STRING=1' '-DUCONFIG_NO_BREAK_ITERATION=0' -I../deps/v8 -I../deps/v8/include -I/node_src/node-v12.16.3/out/Release/obj/gen/generate-bytecode-output-root -I/node_src/node-v12.16.3/out/Release/obj/gen/torque-output-root -I../deps/icu-small/source/i18n -I../deps/icu-small/source/common  -pthread -Wno-unused-parameter -m64 -Wno-return-type -fno-strict-aliasing -m64 -O3 -fno-omit-frame-pointer -fdata-sections -ffunction-sections -O3 -fno-rtti -fno-exceptions -std=gnu++1y -MMD -MF /node_src/node-v12.16.3/out/Release/.deps//node_src/node-v12.16.3/out/Release/obj.target/v8_compiler/deps/v8/src/compiler/common-operator-reducer.o.d.raw   -c
g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make[1]: *** [tools/v8_gypfiles/v8_compiler.target.mk:255: /node_src/node-v12.16.3/out/Release/obj.target/v8_compiler/deps/v8/src/compiler/backend/register-allocator.o] Error 1
make[1]: *** Waiting for unfinished jobs....
rm cdebecbceb1bf63cc03515e4780d6e3f2f050c4d.intermediate c2a439d89d07318f0147e7eef9bcf0841a0fe0f9.intermediate
make: *** [Makefile:101: node] Error 2
The command '/bin/sh -c set -x     && mkdir /src     && apk add --no-cache libstdc++     && apk add --no-cache --virtual .build-deps         binutils-gold         curl         g++         gcc         gnupg         linux-headers         make         python     && curl -o /tmp/s6-overlay-amd64.tar.gz -sSL https://github.com/just-containers/s6-overlay/releases/download/${S6_VERSION}/s6-overlay-amd64.tar.gz     && tar -zxf /tmp/s6-overlay-amd64.tar.gz -C /     && apk add --no-cache nginx     && rm -rf /etc/nginx/default.d     && for server in         ipv4.pool.sks-keyservers.net         keyserver.pgp.com         ha.pool.sks-keyservers.net     ; do         gpg --keyserver $server --recv-keys             94AE36675C464D64BAFA68DD7434390BDBE9B9C5             FD3A5288F042B6850C66B31F09FE44734EB7990E             71DCFD284A79C3B38668286BC97EC7A07EDE3FC1             DD8F2338BAE7501E3DD5AC78C273792F7D83545D             C4F0DFFF4E8C1A8236409D08E73BC641CC11F4C8             B9AE9905FFD7803F25714661B63B535A4C206CA9             77984A986EBC2AA786BC0F66B01FBB92821C587A             8FCCA13FEF1D0C2E91008E09770F7A9A5AE15600             4ED778F539E3634C779C87C6D7062848A1AB005C             A48C2BEE680E841632CD4E44F07496B3EB3C1762             B9E2F5981AA6E0CD28160D9FF13993A75599653C         && break;     done     && mkdir /node_src     && cd /node_src     && curl -o node-${NODE_VERSION}.tar.gz -sSL https://nodejs.org/dist/${NODE_VERSION}/node-${NODE_VERSION}.tar.gz     && curl -o SHASUMS256.txt.asc -sSL https://nodejs.org/dist/${NODE_VERSION}/SHASUMS256.txt.asc     && gpg --verify SHASUMS256.txt.asc     && grep node-${NODE_VERSION}.tar.gz SHASUMS256.txt.asc | sha256sum -c -     && cd /node_src     && tar -zxf node-${NODE_VERSION}.tar.gz     && cd node-${NODE_VERSION}     && ./configure --prefix=${NODE_PREFIX} --without-npm     && make -j$(getconf _NPROCESSORS_ONLN)     && make install     && for server in        ipv4.pool.sks-keyservers.net        keyserver.pgp.com        ha.pool.sks-keyservers.net    ; do        gpg --keyserver $server --recv-keys             6A010C5166006599AA17F08146C2130DFD2497F5         && break;     done     && curl -o /tmp/yarn-${YARN_VERSION}.tar.gz -sSL https://github.com/yarnpkg/yarn/releases/download/${YARN_VERSION}/yarn-${YARN_VERSION}.tar.gz     && curl -o /tmp/yarn-${YARN_VERSION}.tar.gz.asc -sSL https://github.com/yarnpkg/yarn/releases/download/${YARN_VERSION}/yarn-${YARN_VERSION}.tar.gz.asc     && gpg --verify /tmp/yarn-${YARN_VERSION}.tar.gz.asc     && tar -zxf /tmp/yarn-${YARN_VERSION}.tar.gz -C /tmp     && mv -f /tmp/yarn-${YARN_VERSION} ${YARN_PREFIX}     && ln -sf ${YARN_PREFIX}/bin/yarn ${YARN_BINARY}/yarn     && ln -sf ${YARN_PREFIX}/bin/yarnpkg ${YARN_BINARY}/yarnpkg     && apk del .build-deps     && rm -rf         /node_src         /tmp/*         /var/cache/apk/*         /etc/nginx/conf.d/*         /usr/share/man' returned a non-zero code: 2
`

**Comment by izonder** [comment]
Could you please describe your failure scenario with more details:
- what has been doing
- what result was expected
- when it happened
- is it reproducible or heisenbug

**Comment by izonder** [comment]
No feedback, consider as a minor issue
